del *.obj
CALL BTXEC700 "CPU=386" btbig
COPY BTBIG.EXE BT_386.EXE
COPY BTBIG.MAP BT_386.MAP
DEL BTBIG.EXE
DEL BTBIG.MAP

del *.obj
CALL BTXEC700 "CPU=386" bt
COPY BT.EXE BTO_386.EXE
COPY BT.MAP BTO_386.MAP
DEL BT.EXE
DEL BT.MAP

del *.obj
CALL BTXEC700 "CPU=286" btbig
COPY BTBIG.EXE BT_286.EXE
COPY BTBIG.MAP BT_286.MAP
DEL BTBIG.EXE
DEL BTBIG.MAP

del *.obj
CALL BTXEC700 "CPU=286" bt
COPY BT.EXE BTO_286.EXE
COPY BT.MAP BTO_286.MAP
DEL BT.EXE
DEL BT.MAP

del *.obj
CALL BTXEC700 "CPU=86" btbig
COPY BTBIG.EXE BT_86.EXE
COPY BTBIG.MAP BT_86.MAP
DEL BTBIG.EXE
DEL BTBIG.MAP

del *.obj
CALL BTXEC700 "CPU=86" bt
COPY BT.EXE BTO_86.EXE
COPY BT.MAP BTO_86.MAP
DEL BT.EXE
DEL BT.MAP
