.TH BTXE 1 "BinkleyTerm XE"
.SH NAME
BinkleyTerm XE \- fidonet compatible mailer
.SH SYNOPSIS
.B btxe
[config] [debug] [dynam] [info] [mail] [noforce] [poll] [share] [term] [unattended]
.TP
.B btutil
[LNG|CTL|GETHIST] [...]
.SH DESCRIPTION
This document is no real documentation. For full docs please frequest BTXE_DOK
at many BBSs or download them from http://btxe.uue.org/.
.br
Btutil can be used to compile binkleys language and mail.sys-files and import
history-data from some bbs-systems into binkleys history-file. Run btutil
without parameters for help.
.SH BUGS
There may be bugs (see ./doc/*/knwnbugs.* for known bugs). Maybe they are
already fixed, so make sure you have got the latest version of BTXE. If you
find a new bug, please use ./doc/bug_rprt.doc to report it or fix it yourself
and send us a diff (see ./doc/team.lst for contact addresses).
.SH AUTHORS
Binkley 2.60 original version is (c) Vince Perriello, modifications were done
by the BTXE-Team (see startup screen, ./doc/xe_user.doc or btxe.uue.org).
